name: deploy to dev environment
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/README.md'

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: "develop"
      url: "https://opensgs-dev.herokuapp.com"
    steps:
      - uses: actions/checkout@v2
          
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "opensgs-dev"
          heroku_email: "allen.ccccnm@gmail.com"
          usedocker: true