name: deploy to production environment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: "staging"
      url: "https://opensgs-staging.herokuapp.com"
    steps:
      - uses: actions/checkout@v2
          
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "opensgs-staging"
          heroku_email: "allen.ccccnm@gmail.com"
          usedocker: true
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://opensgs.herokuapp.com"
    steps:
      - uses: actions/checkout@v2
          
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "opensgs"
          heroku_email: "allen.ccccnm@gmail.com"
          usedocker: true